export const atsShellCopy = {
  brand: {
    name: "ealana",
    badge: "Flow",
    recruiterWorkspaceFallback: "Recruiter Workspace",
    atsWorkspaceFallback: "Flow Workspace",
  },
  sections: {
    workspace: "Workspace",
    account: "Account",
    organization: "Organization",
    admin: "Admin",
  },
  quickJump: {
    title: "Quick jump",
    buttonLabel: "Jump to pages, workflows, and settings…",
    inputPlaceholder: "Search pages, settings, and Flow workflows…",
    emptyState: "No matching routes.",
  },
  primaryActionLabel: "Post New Job",
  routes: {
    dashboard: {
      label: "Dashboard",
      description: "Recruiter performance, actions, and interview pipeline",
      section: "Workspace",
    },
    applications: {
      label: "Applications",
      description: "Review and move candidates through the pipeline",
      section: "Workspace",
    },
    talentSearch: {
      label: "Discover",
      description: "Find the signal others miss across your talent pool",
      section: "Workspace",
    },
    myJobs: {
      label: "My Jobs",
      description: "Open roles, sourcing, and job operations",
      section: "Workspace",
    },
    clients: {
      label: "Clients",
      description: "Manage client relationships and shared hiring workflows",
      section: "Workspace",
    },
    forms: {
      label: "Forms",
      description: "Application forms and intake flows",
      section: "Workspace",
    },
    email: {
      label: "Email",
      description: "Templates and outreach assets",
      section: "Workspace",
    },
    pricing: {
      label: "Pricing",
      description: "Plans, entitlements, and upgrade options",
      section: "Workspace",
    },
    profileSettings: {
      label: "Profile Settings",
      description: "Personal recruiter profile and preferences",
      section: "Account",
    },
    orgSettings: {
      label: "Org Settings",
      description: "Organization setup and permissions",
      section: "Organization",
    },
    teamMembers: {
      label: "Team Members",
      description: "Seats, roles, and collaborator access",
      section: "Organization",
    },
    billing: {
      label: "Billing",
      description: "Subscription and payment settings",
      section: "Organization",
    },
    organizationAnalytics: {
      label: "Organization Analytics",
      description: "Org-level performance analytics",
      section: "Organization",
    },
    adminDashboard: {
      label: "Admin Dashboard",
      description: "Platform-level controls and oversight",
      section: "Admin",
    },
    jobAnalytics: {
      label: "Job Analytics",
    },
    logout: {
      label: "Logout",
    },
  },
  menu: {
    organizationSettings: "Organization Settings",
    organizationManagement: "Org Management",
  },
} as const;

export const recruiterDashboardCopy = {
  header: {
    eyebrow: "Recruiting Performance",
    title: "Recruiter Dashboard",
    subtitle: "Action-first view of your live pipeline, interviews, and hiring momentum.",
    filterSummaryPrefix: "KPIs filtered by",
    allJobsLabel: "All jobs",
    inviteHiringManager: "Invite Hiring Manager",
  },
  filters: {
    dateRangePlaceholder: "Date range",
    allJobsPlaceholder: "All jobs",
    last7Days: "Last 7 days",
    last30Days: "Last 30 days",
    last90Days: "Last 90 days",
  },
  inviteDialog: {
    title: "Invite Hiring Manager",
    description: "Send an email invitation to collaborate on candidate reviews.",
    emailLabel: "Email",
    nameLabel: "Name",
    optionalLabel: "(optional)",
    emailPlaceholder: "hiring.manager@company.com",
    namePlaceholder: "John Smith",
    cancelLabel: "Cancel",
    submitLabel: "Send Invitation",
    submittingLabel: "Sending...",
    emailRequiredTitle: "Email Required",
    emailRequiredDescription: "Please enter an email address.",
  },
  toasts: {
    inviteSuccessTitle: "Invitation Sent",
    inviteErrorTitle: "Failed to Send Invitation",
  },
  kpis: {
    pipelineHealth: {
      label: "Pipeline Health",
      emptyHint: "Post a job to get started",
      tooltip: "Score based on stage movement, time in stage, drop-offs, and candidates that are stuck in the pipeline.",
    },
    activeRoles: {
      label: "Active Roles",
      secondary: "Open positions",
      tooltip: "Active job requisitions in scope for the current dashboard filter.",
    },
    todaysApps: {
      label: "Today's Apps",
      tooltip: "Applications received today for the selected jobs, compared with the existing weekly baseline already used by this dashboard.",
    },
    firstReview: {
      label: "First Review",
      secondary: "Avg response time",
      tooltip: "Average time from application submitted to the first recruiter action.",
    },
    toInterview: {
      label: "To Interview",
      secondary: "Screen → Interview",
      tooltip: "Conversion rate from screening to interview for applications in the current range.",
    },
  },
  actionsPanel: {
    eyebrow: "Recommended Actions",
    title: "AI Actions",
    updatedFallback: "Updated --",
    syncLabel: "Sync Actions",
    loading: "Loading AI actions...",
    unavailable: "AI actions unavailable",
    sections: {
      candidatesToReview: "Candidates to Review",
      finalStage: "Final Stage",
      feedbackPending: "Feedback Pending",
      lowPipeline: "Low Pipeline",
    },
    urgency: {
      high: "High",
      medium: "Medium",
      low: "Low",
      suffix: "Urgency",
    },
  },
  interviewsPanel: {
    eyebrow: "Interview Calendar",
    title: "Today's Interviews",
    viewCalendar: "View Calendar",
    hint: "Pick a day to inspect upcoming interviews",
    statuses: {
      scheduled: "Scheduled",
      upcoming: "Upcoming",
      completed: "Completed",
    },
    empty: "No interviews scheduled for this day.",
  },
  funnel: {
    eyebrow: "Pipeline Overview",
    title: "Pipeline Stage Distribution",
    description: "Hover each stage to inspect momentum, bottlenecks, and interview throughput for the current pipeline slice.",
    noData: "No data available",
    detailsBadge: "Interview Pipeline Details",
    overviewTitle: "Pipeline Overview",
    snapshotSuffix: "Snapshot",
    avgTimeInStage: "Avg. Time In Stage",
    candidatesInStage: "Candidates In Stage",
    interviewsToday: "Interviews Today",
    stageSnapshot: "Stage snapshot",
    recruiterWideView: "Recruiter-wide view",
  },
} as const;

export const applicationsPageCopy = {
  header: {
    title: "Applications",
    subtitle: "Review and manage candidate applications across all jobs",
  },
  filters: {
    searchPlaceholder: "Search by name, email, or job title...",
    statusPlaceholder: "Filter by status",
    stagePlaceholder: "Filter by stage",
    feedbackPlaceholder: "Filter by feedback",
    ratingPlaceholder: "Min rating",
    allStatus: "All Status",
    allStages: "All Stages",
    allApplications: "All Applications",
    allRatings: "All Ratings",
    unassigned: "Unassigned",
    withFeedback: "With Feedback",
    withoutFeedback: "No Feedback",
    submitted: "Submitted",
    shortlisted: "Shortlisted",
    rejected: "Rejected",
    ratingsPrefix: "⭐",
    onePlus: "1+",
    twoPlus: "2+",
    threePlus: "3+",
    fourPlus: "4+",
    five: "5",
  },
  list: {
    title: "All Applications",
    description: "Review and manage candidate applications",
    emptyFiltered: "No applications match your filters",
    emptyNone: "No applications received yet",
    appliedForPrefix: "Applied for:",
    feedbackLabel: "feedback",
    review: "Review",
    coverLetter: "Cover Letter:",
    aiFitAnalysis: "AI Fit Analysis",
    staleScorePrefix: "Score may be outdated",
  },
  toasts: {
    statusUpdatedTitle: "Application Updated",
    statusUpdatedDescription: "Application status has been updated successfully.",
    updateFailedTitle: "Update Failed",
    stageUpdatedTitle: "Stage updated",
    stageUpdatedDescription: "Application moved to new stage successfully.",
    stageUpdateFailedTitle: "Stage update failed",
  },
} as const;

export const myJobsPageCopy = {
  header: {
    title: "My Jobs",
    subtitle: "Manage your job postings, status, and applications",
    primaryAction: "Post New Job",
  },
  tabs: {
    all: "All Jobs",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending Review",
  },
  searchPlaceholder: "Search by title, company, or location...",
  list: {
    title: "Job Postings",
    description: "Manage your posted job opportunities",
  },
  empty: {
    pendingSingle: "Your job is pending approval",
    pendingMultiplePrefix: "You have",
    pendingMultipleSuffix: "jobs pending approval",
    pendingDescription: "Jobs will appear here once approved by an admin. You'll be notified when they're ready.",
    viewPending: "View Pending Jobs",
    postAnother: "Post Another Job",
    filtered: "No jobs match your filters",
    none: "No job postings yet",
    firstJob: "Post Your First Job",
    hiringManager: "Hiring Manager",
  },
  toasts: {
    publishSuccessTitle: "Job Published",
    publishSuccessDescription: "Your job is now live and accepting applications!",
    publishErrorTitle: "Publish Failed",
  },
} as const;

export const talentSearchPageCopy = {
  header: {
    title: "Memory",
    subtitle: "Everyone your team has already discovered, searchable in plain language — your next hire starts smarter than your last.",
  },
  search: {
    placeholder: "Describe the candidate you're looking for, e.g. 'React developer with 3+ years experience'...",
    buttonLabel: "Search",
    searchingLabel: "Searching candidates...",
    noResultsTitle: "No matching candidates found",
    noResultsHint: "Try a different search query",
    errorFallback: "Search failed. Please try again.",
    hybridScoreHint: "Ranked by hybrid RRF, score shown as cosine semantic match.",
    rankingHint: "Results are ranked using search that analyzes both keywords and the meaning of your query, helping surface the most relevant resumes—not just exact keyword matches.",
    rankingTooltip:
      "We combine keyword scoring with semantic search, then re-rank results using an AI model to find the most relevant matches.",
    emailUnavailable: "Email unavailable",
    matchingResumeSectionsSuffixSingle: "matching resume section",
    matchingResumeSectionsSuffixPlural: "matching resume sections",
    whyMatched: "Why this matched",
    addToJob: "Add to Job",
    resume: "Resume",
    emptyTitle: "Discover",
    resumePreviewFallback: "Resume Preview",
    resumePreviewFrameTitle: "Resume Preview",
    openInNewTab: "Open in New Tab",
    download: "Download",
    unsupportedPreview: "Unable to preview this file type in browser.",
    downloadToView: "Download to View",
    noResume: "No resume available",
  },
} as const;

export const profileSettingsPageCopy = {
  header: {
    title: "Profile Settings",
    subtitle: "Manage your recruiter profile and public visibility",
  },
  cards: {
    basicInformation: {
      title: "Basic Information",
      description: "Your public display information",
      displayName: "Display Name",
      displayNamePlaceholder: "Your display name",
      displayNameHint: "This will be shown on your job postings",
      company: "Company",
      companyPlaceholder: "Your company name",
      phone: "Phone Number",
      phonePlaceholder: "+1 (555) 123-4567",
      location: "Location",
      locationPlaceholder: "City, Country",
      linkedin: "LinkedIn Profile",
      linkedinPlaceholder: "https://linkedin.com/in/your-profile",
    },
    bio: {
      title: "Bio",
      description: "Tell candidates about yourself",
      placeholder: "Write a brief bio about yourself and your recruiting experience...",
    },
    specializations: {
      title: "Specializations",
      description: "Industries or areas you specialize in",
      placeholder: "Add a specialization (e.g., Tech, Healthcare)",
      addLabel: "Add",
      counterSuffix: "/20 specializations",
    },
    visibility: {
      title: "Profile Visibility",
      description: "Control who can see your profile",
      publicProfile: "Public Profile",
      publicProfileHint: "Allow candidates to view your profile and see all your job postings",
    },
  },
  save: {
    idle: "Save Profile",
    pending: "Saving...",
  },
  loading: "Loading profile...",
  toasts: {
    successTitle: "Profile updated",
    successDescription: "Your profile has been saved successfully.",
    errorTitle: "Failed to update profile",
  },
} as const;

export const applicationManagementCopy = {
  header: {
    subtitlePrefix: 'Review and manage applications for',
    pendingApprovalTitle: 'Pending Approval',
    pendingApprovalDescription:
      'This job is waiting for admin approval. It will become visible to candidates once approved. You can still prepare by setting up pipeline stages and reviewing any existing applications.',
    postedPrefix: 'Posted',
    applicationsLabel: 'Applications',
  },
  filters: {
    sortBy: 'Sort by:',
    newestFirst: 'Newest First',
    aiFitScore: 'AI Fit Score',
    stage: 'Stage:',
    allStages: 'All Stages',
    unassigned: 'Unassigned',
    aiAction: 'AI Action:',
    aiActionHelp: "Filter by AI's recommended next step for each candidate",
    notAnalyzed: 'Not Analyzed',
  },
  actions: {
    bulkEmail: 'Bulk Email',
    bulkForm: 'Bulk Form',
    requestHiringManagerReview: 'Request HM Review',
    shareWithClient: 'Share with Client',
    batchInterview: 'Batch Interview',
    addCandidate: 'Add Candidate',
  },
  validation: {
    noCandidatesTitle: 'No candidates selected',
    noCandidatesDescription: 'Select candidates using the checkboxes first.',
    noClientTitle: 'No client linked',
    noClientDescription: 'Set a client for this job before sharing a shortlist.',
    bulkEmailConfirm: (count: number) => `You are about to email ${count} candidates. Proceed?`,
    bulkFormsConfirm: (count: number) => `You are about to send forms to ${count} candidates. Proceed?`,
  },
  dialogs: {
    interview: {
      titlePrefix: 'Schedule Interview',
      description: 'Set interview details for this candidate',
      date: 'Date',
      time: 'Time',
      timePlaceholder: 'e.g., 10:00 AM - 11:00 AM',
      location: 'Location',
      locationPlaceholder: 'e.g., Zoom link or office address',
      notes: 'Notes (Optional)',
      notesPlaceholder: 'Additional notes...',
      submit: 'Schedule Interview',
      submitting: 'Scheduling...',
      scheduledPrefix: 'Interview scheduled for',
      downloadInvite: 'Download Calendar Invite (.ics)',
      downloadInviteHint:
        'Share this file with the interview panel and candidate to add the interview to their calendars',
    },
    email: {
      titlePrefix: 'Send Email',
      description: 'Select a template to send to this candidate',
      template: 'Email Template',
      templatePlaceholder: 'Select template...',
      preview: 'Preview',
      submit: 'Send Email',
      submitting: 'Sending...',
    },
    shortlist: {
      title: 'Share Shortlist with Client',
      description: 'Create a client-ready shortlist link for the selected candidates.',
      client: 'Client',
      noClientLinked: 'No client linked to this job',
      noClientHint: 'Link a client to this job on the job posting to enable sharing.',
      titleLabel: 'Shortlist Title (Optional)',
      titlePlaceholder: 'e.g., Frontend Engineer Shortlist',
      messageLabel: 'Message to Client (Optional)',
      messagePlaceholder: 'Context for this shortlist, expectations, or notes for the client...',
      expiresAt: 'Expires At (Optional)',
      expiresHint: 'Leave blank to keep the shortlist active indefinitely.',
      shareableLink: 'Shareable Link',
      copy: 'Copy',
      close: 'Close',
      create: 'Create Shortlist',
      creating: 'Creating...',
    },
    bulkEmail: {
      titlePrefix: 'Send Bulk Email',
      titleSuffix: 'selected',
      description: 'Choose a template to send to all selected candidates',
      selectAllInView: 'Select all in current view',
      clearSelection: 'Clear selection',
      template: 'Email Template',
      templatePlaceholder: 'Select template...',
      preview: 'Preview',
      submit: 'Send to Selected',
      submitting: 'Sending...',
      progressPrefix: 'Sending',
    },
    bulkForms: {
      titlePrefix: 'Send Bulk Form',
      titleSuffix: 'selected',
      description: 'Choose a form template to send to all selected candidates',
      dailyInviteLimitReached: 'Daily invite limit reached',
      invitesRemainingSuffix: 'invites remaining today',
      usedSuffix: 'used',
      selectAllInView: 'Select all in current view',
      clearSelection: 'Clear selection',
      formTemplate: 'Form Template',
      formTemplatePlaceholder: 'Select form template...',
      formInfo: 'Form Info',
      questionsSuffixSingle: 'question',
      questionsSuffixPlural: 'questions',
      customMessage: 'Custom Message (Optional)',
      customMessagePlaceholder: 'Add a personal message for all selected candidates...',
      customMessageHint: 'This message will be included in the invitation email for all candidates',
      submit: 'Send to Selected',
      submitting: 'Sending...',
      dailyLimitReachedButton: 'Daily limit reached',
      progressPrefix: 'Sending',
    },
    hmReview: {
      title: 'Request Hiring Manager Review',
      description: 'Send the selected candidates to the assigned hiring manager for evaluation.',
      noteLabel: 'Note for hiring manager (optional)',
      notePlaceholder: 'Highlight what you want the hiring manager to assess for this shortlist...',
      noteHint: 'This note appears beside the requested candidates in the hiring manager review queue.',
      cancel: 'Cancel',
      submit: 'Send Review Request',
    },
    batchInterview: {
      title: 'Schedule Batch Interviews',
      description: 'Schedule interviews for the selected candidates. Use an interval to create back-to-back slots.',
      date: 'Date',
      startTime: 'Start time',
      intervalLabel: 'Interval between interviews',
      intervalPlaceholder: 'Interval',
      intervalSameTime: '0 hours (same time)',
      moveToStage: 'Move to stage',
      keepCurrent: 'Keep current',
      location: 'Location',
      locationPlaceholder: 'e.g. Zoom link or office address',
      notes: 'Notes (optional)',
      notesPlaceholder: 'Add any interviewer or candidate instructions...',
      hint:
        "When an interval is set, each candidate will be scheduled in sequence starting from the selected time. Times are based on your browser's local timezone.",
      cancel: 'Cancel',
      submit: 'Schedule Interviews',
      submitting: 'Scheduling...',
    },
    stageHistory: {
      titlePrefix: 'Stage History',
      description: 'Timeline of all stage changes for this application',
      empty: 'No stage history available',
    },
    aiSummary: {
      title: 'Generate AI Summaries',
      description: 'Generate AI-powered candidate summaries with suggested actions.',
      selectedCandidates: 'Selected candidates:',
      willGenerate: 'Will generate:',
      alreadyHaveSummaries: 'Already have summaries (will skip):',
      tooManySelectedTitle: 'Too many selected',
      tooManySelectedDescriptionPrefix: 'Please select 50 or fewer candidates. You have',
      tooManySelectedDescriptionSuffix: 'selected.',
      dailyLimitExceededTitle: 'Daily limit exceeded',
      dailyLimitExceededDescriptionMiddle: 'analyses left today.',
      dailyLimitExceededDescriptionSuffix: 'would be generated. Reduce selection or check "Regenerate" to skip fewer.',
      serviceUnavailableTitle: 'Service Unavailable',
      serviceUnavailableDescription: 'AI service is temporarily unavailable. Please try again later.',
      dailyLimit: 'Daily limit:',
      remaining: 'Remaining:',
      resetsAt: 'Resets at:',
      regenerateTitle: 'Regenerate existing summaries',
      regenerateHint: 'By default, candidates with existing summaries are skipped',
      generating: 'Generating summaries...',
      processedSuffix: 'processed',
      close: 'Close',
      cancel: 'Cancel',
      cancelJob: 'Cancel Job',
      generatePrefix: 'Generate',
      summarySingular: 'Summary',
      summaryPlural: 'Summaries',
      starting: 'Starting...',
    },
  },
  toasts: {
    aiSummaryAllCachedTitle: 'All Selected Have Summaries',
    aiSummaryStartedTitle: 'AI Summary Started',
    aiSummaryCannotStartTitle: 'Cannot Generate Summaries',
    aiSummariesGeneratedTitle: 'AI Summaries Generated',
    aiSummaryFailedTitle: 'Summary Generation Failed',
    statusUpdatedTitle: 'Status updated',
    statusUpdatedDescription: 'Application status has been updated successfully.',
    updateFailedTitle: 'Update failed',
    bulkUpdateSuccessTitle: 'Bulk update successful',
    bulkUpdateFailedTitle: 'Bulk update failed',
    downloadTrackedTitle: 'Download tracked',
    downloadTrackedDescription: 'Resume download has been recorded.',
    stageUpdatedTitle: 'Stage updated',
    stageUpdatedDescription: 'Application moved to new stage successfully.',
    interviewScheduledTitle: 'Interview scheduled',
    interviewScheduledDescription: 'Interview has been scheduled successfully.',
    shortlistCreatedTitle: 'Shortlist Created',
    shortlistCreatedDescription: 'Share this link with your client to review candidates.',
    shortlistFailedTitle: 'Failed to Create Shortlist',
    emailSentTitle: 'Email sent',
    emailSentDescription: 'Email has been sent successfully.',
    bulkEmailSentTitle: 'Bulk email sent',
    bulkEmailFailedTitle: 'Bulk email failed',
    bulkFormsSentTitle: 'Bulk forms sent',
    bulkFormsFailedTitle: 'Bulk forms failed',
    hmReviewRequestedTitle: 'Hiring manager review requested',
    hmReviewRequestedWithIssuesTitle: 'Hiring manager review requested with issues',
    hmReviewRequestFailedTitle: 'Failed to request hiring manager review',
    batchInterviewsScheduledTitle: 'Batch interviews scheduled',
    batchSchedulingFailedTitle: 'Batch scheduling failed',
    noteAddedTitle: 'Note added',
    noteAddedDescription: 'Recruiter note has been added successfully.',
    ratingUpdatedTitle: 'Rating updated',
    ratingUpdatedDescription: 'Candidate rating has been updated successfully.',
    dragCancelledTitle: 'Drag cancelled',
    dragCancelledDescription: 'Drop onto a stage column to move the application.',
    moveFailedTitle: 'Move failed',
    moveFailedDescription: 'Failed to move application. Please try again.',
    invitationSentTitle: 'Invitation sent',
    invitationSentDescription: 'Form invitation has been sent successfully.',
    invitationFailedTitle: 'Failed to send invitation',
    noDataTitle: 'No Data',
    noDataDescription: 'There are no applications to export.',
    exportSuccessTitle: 'Export Successful',
    exportFailedTitle: 'Export Failed',
    exportFailedDescription: 'Failed to export applications.',
    noApplicationsSelectedTitle: 'No applications selected',
    noApplicationsSelectedDescription: 'Please select applications first.',
    bulkMoveCompleteTitle: 'Bulk move complete',
    movedPrefix: 'Moved:',
    failedPrefix: 'Failed:',
    linkCopiedTitle: 'Link Copied',
    linkCopiedDescription: 'Shortlist link copied to clipboard.',
    copyFailedTitle: 'Copy Failed',
    copyFailedDescription: 'Could not copy the link. Please copy it manually.',
    jobCancelledTitle: 'Job Cancelled',
    jobCancelledDescription: 'AI summary generation cancelled.',
    cancelFailedTitle: 'Cancel Failed',
    cancelFailedDescription: 'Could not cancel the job',
  },
} as const;

export const orgSettingsPageCopy = {
  header: {
    title: "Organization Settings",
    subtitle: "Manage your organization's settings and billing information",
    noOrganization: "You are not part of any organization.",
  },
  general: {
    title: "General Settings",
    description: "Basic information about your organization",
    organizationName: "Organization Name",
    organizationNamePlaceholder: "Acme Inc",
    organizationSlug: "Organization Slug",
    ownerOnlyHint: "Only the organization owner can change the name.",
    slugHint: "This is your unique organization identifier.",
    save: "Save Changes",
  },
  domain: {
    title: "Email Domain",
    description: "Claim your company email domain to enable automatic join requests",
    verifiedDescription: "Domain verified - users can request to join",
    pendingDescription: "Pending verification by admin",
    verifiedBadge: "Verified",
    pendingBadge: "Pending",
    emptyState: "No domain claimed yet. Claim your company domain to let employees request to join.",
    requestVerification: "Request Domain Verification",
  },
  billing: {
    title: "Billing Information",
    description: "Information for invoices and tax purposes",
    billingContactName: "Billing Contact Name",
    billingContactNamePlaceholder: "John Doe",
    billingContactEmail: "Billing Contact Email",
    billingContactEmailPlaceholder: "billing@company.com",
    legalName: "Legal Name (for invoices)",
    legalNamePlaceholder: "Company Legal Name LLP",
    gstin: "GSTIN (Optional)",
    gstinPlaceholder: "22AAAAA0000A1Z5",
    gstinHint: "Provide GSTIN if you want it printed on invoices for tax records.",
    billingAddress: "Billing Address",
    billingAddressPlaceholder: "123 Business Street, Suite 100",
    city: "City",
    cityPlaceholder: "Mumbai",
    state: "State",
    statePlaceholder: "Maharashtra",
    pincode: "Pincode",
    pincodePlaceholder: "400001",
    save: "Save Billing Info",
  },
  toasts: {
    settingsSavedTitle: "Settings saved",
    settingsSavedDescription: "Organization name updated successfully.",
    billingSavedTitle: "Billing info saved",
    billingSavedDescription: "Billing information updated successfully.",
    copiedTitle: "Copied",
    copiedDescription: "Copied to clipboard",
    errorTitle: "Error",
    updateSettingsError: "Failed to update settings",
    updateBillingError: "Failed to update billing info",
  },
} as const;

export const orgTeamPageCopy = {
  header: {
    title: "Team Members",
    subtitle: "Manage your organization's team members",
    inviteMember: "Invite Member",
  },
  dialogs: {
    inviteTitle: "Invite Team Member",
    inviteDescription: "Send an invitation to join your organization.",
    noSeatsWarning: "No seats available. Purchase more seats first.",
    emailLabel: "Email Address",
    emailPlaceholder: "colleague@company.com",
    memberRoleHint: "The invited user will join as a Member. You can promote them to Admin after they join.",
    sendInvitation: "Send Invitation",
    manageSeatsTitle: "Manage Seats",
    removeMemberTitle: "Remove Member",
    reassignPlaceholder: "Select a member",
    checkingJobs: "Checking assigned jobs...",
    jobsMustBeReassigned: "This member still owns jobs. Reassign them before removing access.",
    noEligibleAssignee: "No eligible member is available to receive these jobs.",
    removeBlocked: "Reassign jobs to continue",
  },
  sections: {
    members: "Members",
    pendingInvitations: "Pending Invitations",
    pendingInvitationsDescription: "Invitations that haven't been accepted yet",
    noSeat: "No Seat",
  },
  toasts: {
    invitationSentTitle: "Invitation sent",
    invitationResentTitle: "Invitation resent",
    invitationCancelledTitle: "Invitation cancelled",
    seatsReducedTitle: "Seats reduced",
    cannotRemoveOwnerTitle: "Cannot remove owner",
    cannotRemoveOwnerDescription: "The organization owner cannot be removed.",
    memberRemovedTitle: "Member removed",
    memberHasJobsTitle: "Reassign jobs first",
    requestApprovedTitle: "Request approved",
    requestRejectedTitle: "Request rejected",
    errorTitle: "Error",
    inviteError: "Failed to send invitation",
    removeMemberError: "Failed to remove member",
    memberHasJobsError: "This member still owns jobs. Reassign them before removing access.",
    requestError: "Failed to respond to request",
    resendInviteError: "Failed to resend invitation",
    cancelInviteError: "Failed to cancel invitation",
  },
} as const;

export const orgDomainRequestPageCopy = {
  common: {
    noOrganization: "You are not part of any organization.",
    backToSettings: "Back to Settings",
    errorTitle: "Error",
  },
  access: {
    ownerOnly: "Only organization owners can request domain verification.",
  },
  verified: {
    title: "Domain Verified",
    description: "Users with this email domain can now request to join your organization.",
  },
  pending: {
    title: "Domain Verification Pending",
    description: "Your request is being reviewed by an administrator.",
    badge: "Pending",
    hint: "You'll receive a notification once your request is approved or rejected.",
  },
  request: {
    title: "Request Domain Verification",
    description: "Claim your company's email domain to enable automatic join requests from employees",
    publicEmailTitle: "Using a public email",
    publicEmailDescription:
      "You're using a public email domain. You can still claim a company domain, but you'll need to verify ownership.",
    companyDomain: "Company Domain",
    companyDomainPlaceholder: "company.com",
    suggestedPrefix: "Based on your email, we suggest:",
    useThis: "Use this",
    nextTitle: "What happens next?",
    nextSteps: [
      "Your request will be reviewed by an ealana administrator",
      "We may contact you to verify domain ownership",
      "Once approved, users with your company email can request to join",
      "You'll be able to approve or reject join requests",
    ],
    submit: "Submit Request",
  },
  toasts: {
    missingDomain: "Please enter a domain",
    invalidDomainTitle: "Invalid domain",
    invalidDomainDescription: "Please enter a valid domain (e.g., company.com)",
    publicDomainTitle: "Public domain not allowed",
    publicDomainDescription: "Public email domains like gmail.com cannot be claimed.",
    requestSubmittedTitle: "Request submitted",
    requestSubmittedDescription: "Your domain verification request has been submitted for review.",
    submitFailed: "Failed to submit request",
  },
} as const;

export const orgAnalyticsPageCopy = {
  header: {
    title: "Organization Analytics",
    subtitle: "Comprehensive hiring metrics and team performance insights",
  },
  stats: {
    totalApplications: "Total Applications",
    totalHires: "Total Hires",
    conversionRate: "Conversion Rate",
    avgTimeToFill: "Avg Time to Fill",
    avgTimeToFillSubtitle: "Last 90 days",
  },
  sections: {
    timeToFill: {
      title: "Time to Fill by Job",
      description: "Average days from posting to hire (last 90 days)",
      empty: "No hiring data yet",
    },
    timeInStage: {
      title: "Time in Stage Breakdown",
      description: "Average days candidates spend in each stage",
      empty: "No stage data yet",
    },
    sourcePerformance: {
      title: "Source Performance",
      description: "Application sources and their conversion rates (last 90 days)",
      empty: "No source data yet",
    },
    recruiterPerformance: {
      title: "Recruiter Performance",
      description: "Recruiter activity and response times",
      empty: "No recruiter data yet",
    },
    hiringManagerPerformance: {
      title: "Hiring Manager Performance",
      description: "Review turnaround and pending feedback",
      empty: "No hiring manager data yet",
    },
  },
} as const;

export const jobPostPageCopy = {
  loading: "Loading...",
  deniedTitle: "Access Denied",
  deniedDescription: "You need recruiter or admin privileges to post jobs.",
  header: {
    title: "Post a New Job",
    subtitle: "Create your job posting in a few simple steps",
  },
} as const;

export const jobEditPageCopy = {
  toasts: {
    successTitle: "Job updated",
    successDescription: "Job details have been saved successfully.",
    errorTitle: "Update failed",
  },
  empty: {
    title: "Job Not Found",
    description: "The requested job could not be found.",
    back: "Back to Job",
  },
  form: {
    title: "Edit Job Details",
    description: "Update the job posting information",
  },
} as const;

export const jobPipelinePageCopy = {
  back: "Back to Job",
  empty: {
    title: "Job Not Found",
    description: "The requested job could not be found.",
  },
  panel: {
    title: "Pipeline Stages",
    description: "Drag to reorder stages. Click edit to rename.",
    empty: "No pipeline stages configured. Add your first stage below.",
    newStagePlaceholder: "New stage name...",
    addStage: "Add Stage",
    aboutTitle: "About Pipeline Stages",
    tips: [
      "Drag stages to reorder them in your hiring workflow",
      "Stages with candidates show a count badge",
      'Deleting a stage with candidates will move them to "Unassigned"',
      "Stages are shared across all jobs in your organization",
    ],
  },
  deleteDialog: {
    titlePrefix: 'Delete "',
    titleSuffix: '" stage?',
    withCandidatesPrefix: "This stage has",
    withCandidatesMiddle: "candidate",
    withCandidatesMiddlePlural: "candidates",
    withCandidatesSuffix: 'Deleting it will move them to "Unassigned". This action cannot be undone.',
    withoutCandidates: "This stage has no candidates. Are you sure you want to delete it?",
    cancel: "Cancel",
    deleting: "Deleting...",
    delete: "Delete Stage",
  },
  toasts: {
    createdTitle: "Stage created",
    createdDescription: "New pipeline stage has been added.",
    createFailedTitle: "Failed to create stage",
    updatedTitle: "Stage updated",
    updatedDescription: "Pipeline stage has been renamed.",
    updateFailedTitle: "Failed to update stage",
    reorderedTitle: "Stages reordered",
    reorderedDescription: "Pipeline stage order has been updated.",
    reorderFailedTitle: "Failed to reorder stages",
    deletedTitle: "Stage deleted",
    deletedDescription: "Pipeline stage has been removed.",
    deleteFailedTitle: "Failed to delete stage",
  },
} as const;

export const clientsPageCopy = {
  header: {
    title: "Clients",
    subtitle: "Manage client organizations for agency and multi-company recruiting.",
    addClient: "Add Client",
  },
  searchPlaceholder: "Search by name, domain, or contact...",
  list: {
    title: "Client List",
    description: "All clients you manage for job postings and analytics.",
    emptyTitle: "No clients yet",
    emptyDescription: "Add clients to organize roles by company and simplify reporting.",
    columns: {
      name: "Name",
      domain: "Domain",
      primaryContact: "Primary Contact",
      email: "Email",
      notes: "Notes",
      roles: "Roles",
      applications: "Applications",
      actions: "Actions",
    },
    notSet: "Not set",
    edit: "Edit",
  },
  dialog: {
    addTitle: "Add Client",
    editTitle: "Edit Client",
    addDescription: "Create a new client that you can associate jobs with.",
    editDescription: "Update client details for better organization and reporting.",
    name: "Name *",
    namePlaceholder: "Acme Corp",
    domain: "Domain",
    domainPlaceholder: "acme.com",
    contactName: "Primary Contact Name",
    contactNamePlaceholder: "Jane Doe",
    contactEmail: "Primary Contact Email",
    contactEmailPlaceholder: "jane.doe@acme.com",
    notes: "Notes",
    notesPlaceholder: "Key stakeholders, expectations, or special terms...",
    cancel: "Cancel",
    save: "Save",
  },
  toasts: {
    createdTitle: "Client Created",
    createdDescription: "Client has been added successfully.",
    createFailedTitle: "Failed to Create Client",
    createFailedDescription: "An error occurred while creating the client.",
    updatedTitle: "Client Updated",
    updatedDescription: "Client details have been updated successfully.",
    updateFailedTitle: "Failed to Update Client",
    updateFailedDescription: "An error occurred while updating the client.",
    missingNameTitle: "Missing name",
    missingNameDescription: "Client name is required.",
  },
} as const;

export const onboardingPageCopy = {
  steps: {
    org: "Organization",
    profile: "Profile",
    plan: "Plan",
  },
  toasts: {
    creditsTitle: "Credits initialized",
    creditsDescription: "Your AI credits are ready to use.",
  },
  error: {
    title: "Something went wrong",
    description: "We couldn't load your onboarding status. Please try again or contact support if the issue persists.",
    retry: "Try Again",
  },
  header: {
    title: "Welcome to ealana",
    subtitle: "Let's get you set up in just a few steps",
  },
} as const;

export const candidateAuthPageCopy = {
  accessDeniedTitle: "Access Denied",
  accessDeniedDescription: "This login is for candidates only. Please use the recruiter login.",
  hero: {
    title: "Find Your Dream Job",
    subtitle: "Join thousands of professionals who have found their perfect career match through ealana's advanced job platform.",
    features: [
      {
        title: "Smart Job Search",
        description: "Find opportunities that match your skills and preferences",
      },
      {
        title: "Easy Applications",
        description: "Apply to multiple jobs with one-click applications",
      },
      {
        title: "Profile Building",
        description: "Create a standout profile that attracts employers",
      },
      {
        title: "Real-time Updates",
        description: "Get notified about application status and new opportunities",
      },
    ],
    recruiterPrompt: "Are you a recruiter?",
    recruiterLink: "Go to Recruiter Login",
  },
  card: {
    title: "Candidate Access",
    description: "Sign in to your account or create a new profile",
    signIn: "Sign In",
    register: "Register",
    email: "Email",
    emailPlaceholder: "Enter your email",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    firstName: "First Name",
    firstNamePlaceholder: "First name",
    lastName: "Last Name",
    lastNamePlaceholder: "Last name",
    createPasswordPlaceholder: "Create a password",
    signingIn: "Signing in...",
    createAccount: "Create Account",
    creatingAccount: "Creating account...",
  },
} as const;

export const recruiterAuthPageCopy = {
  hero: {
    title: "Recruiter Portal",
    subtitle: "Access powerful tools to manage your job postings, review applications, and find the perfect candidates for your organization.",
    features: [
      {
        title: "Job Management",
        description: "Post, edit, and manage your job listings with ease",
      },
      {
        title: "Application Review",
        description: "Review, shortlist, and manage candidate applications",
      },
      {
        title: "Analytics",
        description: "Track job performance and application metrics",
      },
      {
        title: "Secure Access",
        description: "Enterprise-grade security for your recruitment data",
      },
    ],
    candidatePrompt: "Looking for candidate access?",
    candidateLink: "Go to Candidate Login",
  },
  verification: {
    checkEmailTitle: "Check Your Email",
    checkEmailDescriptionPrefix: "We've sent a verification link to",
    checkEmailHint: "Click the link in the email to verify your account and start using ealana.",
    verifyTitle: "Verify Your Email",
    verifyDescription: "Please verify your email address before signing in.",
    verifyHintPrefix: "Check your inbox at",
    verifyHintSuffix: "for a verification link.",
    resend: "Resend Verification Email",
    sending: "Sending...",
    backToLogin: "Back to Login",
  },
  invite: {
    prefix: "You've been invited to join",
    byPrefix: "Invited by",
    invalid: "Invalid or expired invite link",
    createAccount: "Create Your Account",
    joinPrefix: "Register to join",
    emailLocked: "Email is locked to the invite",
  },
  card: {
    title: "Recruiter Access",
    description: "Sign in to your recruiter account or create a new one",
    signIn: "Sign In",
    register: "Register",
    usernameOrEmail: "Username or Email",
    usernameOrEmailPlaceholder: "Enter your username or email",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    firstName: "First Name",
    firstNamePlaceholder: "First name",
    lastName: "Last Name",
    lastNamePlaceholder: "Last name",
    email: "Email *",
    emailPlaceholder: "Enter your email address",
    createPasswordPlaceholder: "Create a strong password",
    signingIn: "Signing in...",
    creatingAccount: "Creating account...",
    createRecruiterAccount: "Create Recruiter Account",
  },
  toasts: {
    verificationSentTitle: "Verification email sent",
    verificationSentDescription: "Please check your inbox.",
    errorTitle: "Error",
    verificationFailed: "Failed to send verification email. Please try again.",
  },
} as const;

export const adminFormResponsesPageCopy = {
  header: {
    title: "Form Responses",
    subtitle: "View and manage all form responses across candidates",
    export: "Export CSV",
  },
  stats: {
    totalResponses: "Total Responses",
    today: "Today",
    avgResponseTime: "Avg Response Time",
    completionRate: "Completion Rate",
    notAvailable: "N/A",
  },
  filters: {
    searchPlaceholder: "Search by candidate name or email...",
    formPlaceholder: "Filter by form",
    allForms: "All Forms",
    statusPlaceholder: "Status",
    allStatus: "All Status",
    answered: "Answered",
    viewed: "Viewed",
    sent: "Sent",
    expired: "Expired",
  },
  list: {
    title: "Responses",
    empty: "No form responses found",
    candidate: "Candidate",
    form: "Form",
    status: "Status",
    submitted: "Submitted",
    actions: "Actions",
    view: "View",
    pagePrefix: "Page",
    of: "of",
  },
  detail: {
    fallbackTitle: "Form Response",
    submittedByPrefix: "Submitted by",
    onPrefix: "on",
    viewUploadedFile: "View Uploaded File",
    noAnswer: "No answer provided",
  },
  toasts: {
    exportCompleteTitle: "Export Complete",
    exportCompleteDescription: "Form responses exported successfully.",
    exportFailedTitle: "Export Failed",
  },
} as const;

export const adminAIJobsPageCopy = {
  header: {
    title: "AI Queue Management",
    subtitle: "Monitor and manage AI processing jobs",
    refresh: "Refresh",
  },
  queues: {
    interactive: "Interactive Queue",
    batch: "Batch Queue",
    waiting: "Waiting",
    active: "Active",
    completed: "Completed",
    failed: "Failed",
  },
  jobs: {
    title: "Active & Pending Jobs",
    description: "Jobs currently in the queue or recently failed",
    empty: "No pending or failed jobs",
    id: "ID",
    status: "Status",
    queue: "Queue",
    userId: "User ID",
    progress: "Progress",
    created: "Created",
    error: "Error",
    actions: "Actions",
  },
  cancelDialog: {
    title: "Cancel AI Job?",
    description: "This will cancel the selected AI job if it is still pending or active.",
  },
  toasts: {
    cancelledTitle: "Job Cancelled",
    cancelledDescription: "The AI job has been cancelled successfully.",
    errorTitle: "Error",
  },
} as const;

export const adminDomainClaimsPageCopy = {
  header: {
    title: "Domain Claims",
    subtitle: "Review and approve domain verification requests",
  },
  stats: {
    title: "Pending Claims",
    awaitingReviewSuffix: "awaiting review",
    pendingSuffix: "pending",
  },
  list: {
    title: "Pending Domain Claims",
    description: "Verify that organizations own the domains they're claiming",
    empty: "No pending domain claims",
    columns: {
      domain: "Domain",
      organization: "Organization",
      requestedBy: "Requested By",
      requested: "Requested",
      actions: "Actions",
    },
  },
  rejectDialog: {
    title: "Reject Domain Claim",
    description: "Add an optional note explaining why this claim is being rejected.",
    reasonLabel: "Rejection reason",
    reasonPlaceholder: "Explain why this claim is being rejected...",
  },
  toasts: {
    approvedTitle: "Claim approved",
    approvedDescription: "The domain claim has been approved.",
    rejectedTitle: "Claim rejected",
    rejectedDescription: "The domain claim has been rejected.",
    errorTitle: "Error",
    errorDescription: "Failed to respond to claim",
  },
} as const;

export const adminSubscriptionsPageCopy = {
  header: {
    title: "Subscriptions",
    subtitle: "Manage organization subscriptions and view analytics",
  },
  stats: {
    mrr: "Monthly Recurring Revenue",
    activeSubscriptions: "Active Subscriptions",
    totalSeats: "Total Paid Seats",
    totalSubscriptions: "Total Subscriptions",
    planDistribution: "Plan Distribution",
  },
  filters: {
    statusPlaceholder: "Filter by status",
    allStatuses: "All Statuses",
    active: "Active",
    cancelled: "Cancelled",
    pastDue: "Past Due",
    trial: "Trial",
  },
  list: {
    title: "All Subscriptions",
    empty: "No subscriptions found",
    organization: "Organization",
    plan: "Plan",
    billing: "Billing",
    seats: "Seats",
    periodEnd: "Period End",
    status: "Status",
    actions: "Actions",
  },
  extendDialog: {
    title: "Extend Subscription",
    description: "Extend access for this organization by adding days to the current billing period.",
    daysLabel: "Extend by days",
    reasonLabel: "Reason",
    reasonPlaceholder: "Explain why this subscription is being extended...",
    confirm: "Extend Subscription",
  },
  toasts: {
    successTitle: "Subscription extended",
    errorTitle: "Error",
    errorDescription: "Failed to extend subscription",
  },
} as const;

export const orgBillingPageCopy = {
  header: {
    title: "Billing & Subscription",
    subtitle: "Manage your subscription, seats, and billing",
  },
} as const;

export const jobSourcingPageCopy = {
  header: {
    title: "Discover",
    searching: "Searching for candidates...",
    enriching: "Enrichment in progress...",
    action: "Find Candidates",
    actionRefresh: "Refresh data",
    actionPending: "Searching...",
  },
  emptyState: {
    title: "Find top candidates for this role",
  },
} as const;

export const bulkResumeImportPageCopy = {
  header: {
    title: "Bulk Resume Import",
    reparse: "Re-parse",
    applications: "Applications",
  },
} as const;

export const hiringManagerDashboardCopy = {
  header: {
    title: "Hiring Manager Dashboard",
    subtitlePrefix: "Welcome back,",
    subtitleSuffix: "Review candidates and provide feedback.",
  },
  stats: {
    myJobs: "My Jobs",
    myJobsHint: "Jobs assigned to you",
    totalCandidates: "Total Candidates",
    totalCandidatesHint: "Across all your jobs",
    requestedReviews: "Requested Reviews",
    requestedReviewsHint: "Candidates explicitly sent to you by recruiters",
    awaitingFeedback: "Awaiting Feedback",
    awaitingFeedbackHint: "Requested candidates still waiting on your decision",
  },
  sections: {
    myJobs: "My Jobs",
    loadingJobs: "Loading jobs...",
    emptyJobs: "No jobs assigned to you yet.",
    emptyJobsHint: "Contact your recruiter to get assigned to job postings.",
  },
} as const;

export const hiringManagerReviewPageCopy = {
  header: {
    back: "Back to Dashboard",
    title: "Candidate Review",
    subtitle: "Review recruiter-requested candidates, inspect their resumes, and leave structured feedback.",
  },
  sections: {
    candidates: "Candidates",
    feedback: "Feedback",
    loading: "Loading candidates...",
    empty: "No candidates found for this job yet.",
    emptyHint: "Once applications arrive, you can review them here.",
    inaccessibleJob: "This job is no longer available for your review.",
    chooseCandidate: "Select a candidate to review their profile and feedback.",
    noRequestedReviews: "No candidates are waiting for your review yet.",
    noRequestedReviewsHint: "Recruiters can request your feedback from the job applications page once they have a focused shortlist for you.",
    awaitingFeedback: "Awaiting feedback",
    alreadyReviewed: "Reviewed by you",
    recruiterContext: "Recruiter context",
    resume: "Resume",
    viewResume: "Open Resume",
    downloadResume: "Download Resume",
    resumePreviewFallback: "Inline preview is available for PDF resumes. Use the buttons above to open or download this file.",
  },
  stats: {
    totalCandidates: "Total Candidates",
    requestedReviews: "Requested Reviews",
    awaitingFeedback: "Awaiting Your Feedback",
  },
} as const;

export const candidateDashboardCopy = {
  header: {
    titlePrimary: "Candidate",
    titleSecondary: "Dashboard",
    subtitle: "Manage your profile and track your job applications with AI-powered insights",
  },
  alerts: {
    fitUnavailable: "AI-powered job fit scoring is currently unavailable. You can still view and manage your applications.",
    resumeUnavailable: "AI resume advisor is currently unavailable. Standard resume uploads are still available.",
    fitComputations: "Free AI Fit Computations",
  },
} as const;

export const adminSuperDashboardCopy = {
  header: {
    title: "Admin Super Dashboard",
    subtitle: "Complete platform control and management",
    organizations: "Organizations",
    subscriptions: "Subscriptions",
  },
} as const;

export const unifiedAdminDashboardCopy = {
  header: {
    title: "Admin Control Center",
    subtitle: "Complete platform management, testing, and analytics dashboard",
  },
} as const;

export const jobAnalyticsPageCopy = {
  header: {
    backToJob: "Back to Job",
    notFoundTitle: "Job Not Found",
    notFoundDescription: "The requested job could not be found.",
  },
  sections: {
    reviewed: "Reviewed",
    rejected: "Rejected",
    attentionNeeded: "Attention Needed",
    clientFeedback: "Client Feedback",
    clientFeedbackDescription: "Shortlists shared with clients and their feedback",
    sentToClients: "Sent to Clients",
    advanced: "Advanced",
    onHold: "On Hold",
    shortlists: "Shortlists",
  },
} as const;
