[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.pip",
  "python312Packages.virtualenv",
  "gcc",
  "glib",
  "gobject-introspection",
  "cairo",
  "pango",
  "gdk-pixbuf"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = ". /opt/venv/bin/activate && python manage.py collectstatic --noinput && python manage.py migrate && waitress-serve --host=0.0.0.0 --port=$PORT --threads=4 TRM.wsgi:application"
