[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.pip",
  "gcc",
  "glib",
  "gobject-introspection",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "pkg-config"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "python manage.py collectstatic --noinput && python manage.py migrate && waitress-serve --host=0.0.0.0 --port=$PORT --threads=4 TRM.wsgi:application"
